"""empty message

Revision ID: 38bcb29b4f77
Revises: b2b3625e3f88
Create Date: 2018-01-15 14:14:16.640810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bcb29b4f77'
down_revision = 'b2b3625e3f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('email', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'email')
    # ### end Alembic commands ###
