"""empty message

Revision ID: b2b3625e3f88
Revises: 60cde192eb02
Create Date: 2018-01-15 14:05:17.623980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b3625e3f88'
down_revision = '60cde192eb02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('phone', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cms_user', 'phone')
    # ### end Alembic commands ###
